# get node 16 image
FROM node:16.16.0-alpine
# install git
RUN apk add --update git
RUN git clone https://github.com/cypress-io/cypress-realworld-app.git && cd cypress-realworld-app
WORKDIR /cypress-realworld-app
#install yarn 1.22.10
# RUN npm install yarn@1.22.10 -g
# install application using yarn
RUN yarn install
EXPOSE 3000
EXPOSE 3001
#Start the application
ENTRYPOINT [ "yarn","start"]
# build the image
# docker build -t georgesutaru/test_the_framework:cypress_realworldapp -f Dockerfile_Cypress_realworldapp .

#run the image
# docker run --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=NODE_VERSION=16.16.0 --env=YARN_VERSION=1.22.19 --workdir=/cypress-realworld-app -p 3001:3000 -p 3002:3001 --runtime=runc -d georgesutaru/test_the_framework:realwordapp